# Generated by Django 4.2.4 on 2023-10-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarComments',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_comments', to='api.timelinebar')),
            ],
        ),
    ]
