# Generated by Django 4.2.4 on 2023-10-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelinebar',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='scrap',
            name='timeline_bar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to='api.timelinebar'),
        ),
        migrations.AddField(
            model_name='timelinebar',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='timelinebar',
            name='reason',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
