# Generated by Django 4.2.4 on 2023-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='shift',
            name='total_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_scrap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_slow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_stopped',
            field=models.IntegerField(default=0),
        ),
    ]
