# Generated by Django 4.2.4 on 2023-10-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinebar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timelinebar',
            name='reason',
        ),
    ]
