# Generated by Django 4.2.4 on 2023-11-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.IntegerField(choices=[(1, 'success'), (2, 'warning'), (3, 'danger'), (4, 'no info')], default=4),
        ),
    ]
