# Generated by Django 4.2.4 on 2023-10-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productionline_id_alter_shift_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
