# Generated by Django 4.2.4 on 2023-10-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_timelinebar_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinebar',
            name='hour',
            field=models.TimeField(null=True),
        ),
    ]
