# Generated by Django 4.2.4 on 2023-10-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timelinebar_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinebar',
            name='hour',
            field=models.TimeField(),
        ),
    ]
