# Generated by Django 4.2.4 on 2023-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timelinebar_has_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='autobag_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='molding_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pleating_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(),
        ),
    ]
