# Generated by Django 4.2.4 on 2023-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_options_order_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinebar',
            name='loss',
            field=models.FloatField(null=True),
        ),
    ]
