# Generated by Django 4.2.4 on 2023-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_timelinebar_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinebar',
            name='time_length',
            field=models.FloatField(default=0),
        ),
    ]
