# Generated by Django 4.2.4 on 2023-11-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_timelinebar_time_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinebar',
            name='time_length',
        ),
    ]
