# Generated by Django 4.2.4 on 2023-11-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_timelinebar_parts_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioninfo',
            name='item_count',
            field=models.FloatField(),
        ),
    ]
