# Generated by Django 4.2.4 on 2023-12-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_shift_loss_slow_shift_loss_stopped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninfo',
            name='timeline_bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_bar', to='api.timelinebar'),
        ),
    ]
