# Generated by Django 4.2.4 on 2023-12-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_productioninfo_timeline_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioninfo',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productioninfo',
            name='timeline_bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='api.timelinebar'),
        ),
    ]
