# Generated by Django 4.2.4 on 2023-12-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_productioninfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('made', models.IntegerField(default=0)),
                ('scrap', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_segment', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_segment', to='api.product')),
            ],
        ),
    ]
