# Generated by Django 4.2.4 on 2023-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ordersegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='scrap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='start',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='OrderSegment',
        ),
    ]
