# Generated by Django 4.2.4 on 2023-12-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_shift_rate_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='rate_per_hour',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
