# Generated by Django 4.2.4 on 2023-12-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_timelinebar_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='product',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
