# Generated by Django 4.2.4 on 2023-12-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_scrap_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bars_scrap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='loss_slow',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='loss_stopped',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='minutes_slow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='minutes_stopped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_slow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_stopped',
            field=models.IntegerField(default=0),
        ),
    ]
