# Generated by Django 4.2.4 on 2023-12-08 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_bars_scrap_order_loss_slow_order_loss_stopped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bars_scrap',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loss_slow',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loss_stopped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='made',
        ),
        migrations.RemoveField(
            model_name='order',
            name='minutes_slow',
        ),
        migrations.RemoveField(
            model_name='order',
            name='minutes_stopped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scrap',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_slow',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_stopped',
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.IntegerField(default=0)),
                ('scrap', models.IntegerField(default=0)),
                ('bars_scrap', models.IntegerField(default=0)),
                ('total_slow', models.IntegerField(default=0)),
                ('minutes_slow', models.IntegerField(default=0)),
                ('loss_slow', models.FloatField(default=0)),
                ('total_stopped', models.IntegerField(default=0)),
                ('minutes_stopped', models.IntegerField(default=0)),
                ('loss_stopped', models.FloatField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.order')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.shift')),
            ],
        ),
    ]
