# Generated by Django 4.2.4 on 2023-12-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_order_bars_scrap_remove_order_loss_slow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='bars_scrap',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='loss_slow',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='loss_stopped',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='minutes_slow',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='minutes_stopped',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='total_parts',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='total_scrap',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='total_slow',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='total_stopped',
        ),
    ]
