# Generated by Django 4.2.4 on 2023-12-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_shift_bars_scrap_remove_shift_loss_slow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='reference_line',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
