# Generated by Django 4.2.4 on 2023-12-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_shift_reference_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='rate_per_hour',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='reference_line',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
