# Generated by Django 4.2.4 on 2023-12-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_shift_rate_per_hour_alter_shift_reference_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='reference_line',
        ),
    ]
