# Generated by Django 4.2.4 on 2023-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_order_end_alter_order_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
