# Generated by Django 4.2.4 on 2023-12-20 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_order_end_alter_order_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninfo',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
    ]
