# Generated by Django 4.2.4 on 2023-12-20 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_productioninfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioninfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 17, 36, 26, 905789, tzinfo=datetime.timezone.utc)),
        ),
    ]
