# Generated by Django 4.2.4 on 2023-12-20 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_productioninfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinebar',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 19, 27, 42, 866656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productioninfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 19, 27, 42, 867653, tzinfo=datetime.timezone.utc)),
        ),
    ]
