# Generated by Django 4.2.4 on 2023-12-21 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_timelinebar_date_alter_productioninfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productioninfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 21, 16, 48, 21, 758883, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timelinebar',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 21, 16, 48, 21, 758883, tzinfo=datetime.timezone.utc)),
        ),
    ]
