# Generated by Django 4.2.4 on 2023-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_order_end_date_alter_productioninfo_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
