# Generated by Django 4.2.4 on 2024-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_order_end_date_order_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='number',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=1),
        ),
    ]
